### ISSUE TITLE
No circled

### ISSUE THREAD

**Issue by Leeeeerich** [vivchar/ViewPagerIndicator#6]
Hi! I have some problem with visual indicator, it is not circle.

How fix it?

![Screenshot_1566976417](https://user-images.githubusercontent.com/26391015/63833895-ba493b80-c97c-11e9-88bb-bbb5825a26c0.png)

**Comment by vivchar** [comment]
Hi, I can't help, because you did not provide any code. Looks like you need to use "wrap_content"

**Comment by Leeeeerich** [comment]
Hi, thanks! 
I solved this problem: app:itemScale="1.33" to 1.25.
P.S. Maybe add this warning to the description?
